version: '3.1'

services:
  db:
    image: mongo
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_INITDB_DATABASE: social-media
    ports:
      - "27017:27017"
    volumes:
      - data:/var/lib/mongo/data

volumes:
  data: